services:
  localstack:
    networks:
      - localstack
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.12.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - ACTIVATE_PRO=0
      - DEBUG=1
      - AWS_REGION=us-east-1
      - AWS_ACCOUNT_ID=000000000000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=ls-JIRu0752-liKa-paYA-2551-dexIxEKA028e
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./localstack/scripts/resources.sh:/etc/localstack/init/ready.d/resources.sh"
      - ./lambda/resource/package/app.zip:/lambda/app/app.zip:ro
      - ./lambda/resource/properties/cors-config.json:/lambda/app/cors-config.json:ro
    entrypoint: /bin/sh -c "chmod +x /etc/localstack/init/ready.d/resources.sh && docker-entrypoint.sh"  

  front:
    networks:
      - localstack
    container_name: "front"
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - localstack
  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok_tunnel
    depends_on:
      - front
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: '34qaauGvXP7Omtd8OUtOGESCioS_5b5ucycKKKmD31zr5TtBY'
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    networks:
      - localstack

networks:
  localstack:
    driver: bridge
