map $http_origin $allow_origin {
    default "";
    "~^http://localhost(:[0-9]+)?$"  $http_origin;
    "~^http://localstack(:[0-9]+)?$" $http_origin;
    "https://ivan-unproclaimed-hosea.ngrok-free.dev" $http_origin;
}

server {
    listen 80;

    # Frontend estático
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para o LocalStack
    location /api/ {
        proxy_pass http://localstack:4566/;
        proxy_set_header Host app.lambda-url.us-east-1.localhost.localstack.cloud;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_intercept_errors on;

        add_header Access-Control-Allow-Origin $allow_origin always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, PATCH, OPTIONS" always;
        add_header Access-Control-Allow-Headers "*" always;

        # Responde preflight OPTIONS direto no nginx
        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin $allow_origin always;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, PATCH, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;
            add_header Content-Length 0;
            return 204;
        }
    }
}